name: Deploy Project

on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger deployment
        if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Deployment Success Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() && !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
        with:
          severity: info
          text: A new version of your app has been deployed
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deployment Failure Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() && !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
        with:
          severity: error
          text: Build failed
          details: commit ${{ github.event.push.head }} by ${{ github.actor }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
