name: Install Dependencies

on: workflow_call

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (client)
        working-directory: ./client
        run: npm install

      - name: Install dependencies (server)
        working-directory: ./server
        run: npm install
