name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Set environment variables
        env:
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
        run: echo "TEST_DB_URI=${{ secrets.TEST_DB_URI }}" >> $GITHUB_ENV

      - name: Run client linting
        working-directory: ./client
        run: npm run lint

      - name: Run server linting
        working-directory: ./server
        run: npm run lint

      - name: Run client test
        working-directory: ./client
        run: npm run test

      - name: Run server test
        working-directory: ./server
        run: npm run test

      - name: Run server build
        working-directory: ./server
        run: npm run build

      - name: Start server
        working-directory: ./server
        run: nohup npm start

      - name: run e2e test
        working-directory: ./client
        run: npm run test:e2e
