name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      DB_URI: ${{ secrets.DB_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Run client linting
        working-directory: ./client
        run: npm run lint

      - name: Run server linting
        working-directory: ./server
        run: npm run lint

      - name: Run client test
        working-directory: ./client
        run: npm run test

      - name: Run server test
        working-directory: ./server
        run: npm run test

      - name: Run server build
        working-directory: ./server
        run: npm run build

      - name: Install Playwright browsers
        run: |
          cd client
          npx playwright install --with-deps

      - name: Start server
        working-directory: ./server
        run: nohup npm run start:test &

      - name: Wait for server to start
        run: sleep 5

      - name: Check server status
        run: curl -I http://localhost:3001/api/blogs || exit 1

      - name: Run e2e test
        working-directory: ./client
        run: npm run test:e2e

       - name: Debug Webhook Response
        run: |
          echo 'Sending test message to Discord'
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Test message from GitHub Actions"}' ${{ secrets.DISCORD_WEBHOOK }} -v

      - name: Collaboration Invite Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          text: Hi @mlukkai, pease, I sent you an invite to review my pull request for CI/CD module. invite link https://github.com/pragmaticAweds/fs-open-blog-ci-cd/invitations, Thanks.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Trigger deployment
        if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
